---
title: 'Dealing with the "Packages in Suggests should be used conditionally" email'
author: "Noah Greifer"
date: "2022-06-26"
draft: true
categories:
  - R
  - package development
description: "I show you how to make your R package immune to its Suggested packages being removed from CRAN, saving you from dependency hell."
comments:
  giscus:
    repo: ngreifer/ngreifer.github.io
    repo-id: R_kgDOH8WJeg
    category: Blog comments
    category-id: DIC_kwDOH8WJes4CkT3N
    mapping: pathname
    reactions-enabled: true
    input-position: top
    theme: preferred_color_scheme
    language: en
---

As an R package developer, you may one day receive a dreaded email from Prof. Brian Ripley at CRAN that looks something like this:

> Dear maintainer,
>
> Please see the problems shown on <https://cran.r-project.org/web/checks/check_results_WeightIt.html>.
>
> Please correct before 2022-06-23 to safely retain your package on CRAN.
>
> Packages in Suggests should be used conditionally: see 'Writing R Extensions'. This needs to be corrected even if the missing package(s) become available. It can be tested by checking with \_R\_CHECK\_DEPENDS\_ONLY\_=true.
>
> The CRAN Team

The key message of this email is, "if you don't fix these problems, your package will be taken down from CRAN in two weeks," which is pretty scary, especially if this is your first R package. Although there are many reasons why you might get an email like this, in this post I want to address the specific problem identified by the sentence "Packages in Suggests should be used conditionally".

When writing an R package, the DESCRIPTION file contains metadata bout your package, including its name, a description of the package, and several lists of other packages that your package depends on in some way. There are 4 ways for your package to depend on another package, depending on how your package uses other package's functions, which are named in the DESCRIPTION file: `Depends`, `Imports`, `Suggests`, and `Enhances.`

Packages listed in `Depends` are installed when a user installs your package and are attached when a user loads your package (e.g., using `library()`). Packages listed in `Imports` are installed when a user installs your package and are loaded when a user loads your package. Packages in `Suggests` are not installed when a user installs your package but are loaded by CRAN when performing CRAN checks. (I'll skip `Enhances` because it basically is the same as `Suggests`.)

You probably shouldn't use `Depends`, but `Imports` contains the packages that are necessary for your package to run. For example, my package `WeightIt` needs `ggplot2` for some of its core functionality (plotting the distribution of estimated weights), so `ggplot2` is in `Imports`. The packages in `Suggests`, though are not necessary for the core functionality of your package. They may be only used in examples in the documentation, in the package vignettes, or in methods that are not central to your package's operation. For example, `WeightIt` has `gbm` in `Suggests` because `gbm` is used in one of the documentation examples and is used when a user requests generalized boosted modeling to be used to estimate propensity scores, but GBM is not the only method a user can select and not the default method. That means the user doesn't have to have `gbm` installed to use any of `WeightIt`'s core functionality; the package is truly optional. This is what CRAN expects from packages listed in `Suggests`, anyway. Your package should be able to be built and checked without the packages in `Suggested` installed.

When you receive an email like the one above, this means that the packages you included in `Suggests` are not being used as intended.

*(This post is a draft and is not yet complete.)*
